만국박람회 [STEP 1] claire.pp, cheshire.kwon
2022NewKrew/ios-exposition-universelle-k pull request #4
Opened 2022-01-10 08:55 UTC by yeokyeong46

# 만국박람회 [STEP 1] claire.pp, cheshire.kwon
리뷰어 @wonhee009 

안녕하세요~~ STEP 1 PR 입니다.
## STEP 1
- 구조체 데이터 타입 2개 생성 (박람회 정보, 출품작 정보)
- JSON 디코더 기능 추가 (decodeEntry)

## json 디코더 (decodeEntry)
- entry, exposition data 각각을 디코딩 할 경우 코드가 비슷한 코드가 중복되어서 제네릭을 이용하여 하나의 함수로 합쳤습니다.

## 궁금한 점
* decodeEntry 함수를 이용하여 박람회와 출품작 정보 json 을 모두 디코딩 하려고 do-catch 문을 중첩해서 사용하였는데, 이런 방식으로 중첩해서 써도 되는지 궁금합니다. 또는 이렇게 쓰는것보단 서로 다른 함수를 정의해서 사용하는 방법이 더 좋을까요? 혹은 더 좋은 방법이 있다면 소개부탁드립니다.

2022-01-10 13:37 UTC, wonhee009 requested changes
스텝1 수고하셨습니다!👍
짜잘한 코멘트와 고민점으로 남겨주신 `decode` 관련해서 코멘트 남겨두었습니다🙏

2022-01-10 13:37 UTC, wonhee009 commented on Expo1900/Expo1900/EntryData.swift
> +struct EntryData: Codable{
```suggestion
struct EntryData: Codable {
```

2022-01-10 13:37 UTC, wonhee009 commented on Expo1900/Expo1900/EntryData.swift
> +struct EntryData: Codable{
`Codable`을 채택하셨네요🎉
[공식 문서](https://developer.apple.com/documentation/swift/codable)도 한 번 살펴 보시면 좋을거 같습니다😀
(Codable이 어떤 프로토콜들로 이뤄져 있고, 각각의 프로토콜이 어떤 역할을 하는지에 대해서 살펴 보시면 좋을거 같습니다!☺️)

2022-01-10 13:37 UTC, wonhee009 commented on Expo1900/Expo1900/ExpositionData.swift
> +    let visitors: Int
visitors보다는 visitorsCount처럼 좀 더 명확한 네이밍은 어떨까요?
visitors만 봤을때에는 방문자의 어떤것을 의미하는지에 대해서 의문이 생기는거 같습니다😀

2022-01-10 13:37 UTC, wonhee009 commented on Expo1900/Expo1900/ViewController.swift
>  class ViewController: UIViewController {
화면 구현도 어느정도 하셨네요☺️
스텝2부터 화면 구현으로 알고 있는데 몇 가지 코멘트 남겨두겠습니다!

2022-01-10 13:37 UTC, wonhee009 commented on Expo1900/Expo1900/ViewController.swift
> +    var entryItems:[EntryData] = []
```suggestion
    var entryItems: [EntryData] = []
```

2022-01-10 13:37 UTC, wonhee009 commented on Expo1900/Expo1900/ViewController.swift
> +    var expositionData: [ExpositionData] = []
`expositionData`를 Array로 구성하신 이유가 있으실까요?☺️

2022-01-10 13:37 UTC, wonhee009 commented on Expo1900/Expo1900/ViewController.swift
> +}
현재 2중 do-catch로 exposition, entry를 디코딩하고 있네요.
exposition과 entry의 타입이 상이해서 생긴 고민점이라고 생각이 드는데요.
제네릭을 통해 공통화해서 사용하고 싶다면 타입을 맞춰주는게 맞다고 생각이 듭니다.
다만, 현재는 decode 메서드 안에서 타입을 맞춰주고 있는데 모델의 타입을 맞추는건 어떨까요?
```swift
struct EntryListData: Codable {
     let entrys: [EntryData]
     ...
}
```
이런식으로요.
그러면 `decodeEntry`의 2중 do-catch도 걷어낼 수 있을거 같습니다.

2022-01-11 02:42 UTC, HanEun-ji commented on Expo1900/Expo1900/ViewController.swift
> +    var expositionData: [ExpositionData] = []
decodeEntry의 리턴 타입을 동일하게 하려다보니 expositionData도 배열에 감쌌습니다. 지금은 decodeEntry도 수정하면서 바꾸었습니다!

2022-01-11 02:43 UTC, yeokyeong46 commented on Expo1900/Expo1900/ExpositionData.swift
> +    let visitors: Int
앗 그렇겟네요..! 네이밍 수정했습니다!

2022-01-11 02:43 UTC, yeokyeong46 commented on Expo1900/Expo1900/ViewController.swift
> +}
타입을 넘기는 방향으로 해당 함수 수정했습니다!

2022-01-11 02:44 UTC, yeokyeong46 commented
@wonhee009 @HanEun-ji 
코멘트 주신 내용 반영하여 새로 커밋해두었습니다!! 감사합니다!!!!

2022-01-11 03:01 UTC, wonhee009 approved these changes
@yeokyeong46 @HanEun-ji 
스텝1 수고하셨습니다!🎉
(resolve 안 된 코멘트는 확인하신 후 스텝 2에 반영해주시면 좋겠습니다👍)

2022-01-11 03:02 UTC, merged